#%RAML 1.0 NamedExample
value:
  incidentId: "INC0010002"
  sys_id: "a83820b58f723300e7e16c7827bdeed2"
  description: "Cannot sign into the company portal app"
  comments: "I've already reset my password"
  priority: "Moderate"
  state: "New"
  urgency: "Medium"
  impact: "Medium"
