#%RAML 1.0 NamedExample
value:
  incidentId: "INC0010009"
  sys_id: "9d5e16de97f171107929f8a6f053af69"
  description: "Email server is down"
  comments: "It happened right after the security update"
  priority: "Critical"
  state: "In Progress"
  urgency: "High"
  impact: "High"
